security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto
    providers:
        demo_users:
            memory:
                users:
                    debugger:
                        password: debug
                        roles: ['ROLE_HOT_RELOAD', 'ROLE_USER']
                    viewer:
                        password: viewer
                        roles: ['ROLE_USER']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: demo_users
            form_login:
                login_path: login
                check_path: login
                default_target_path: demo_debug
                enable_csrf: true
            logout:
                path: logout
                target: homepage
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/debug, roles: ROLE_USER }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@dev:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext
